# LG-LACAM random-10-10 experiment configuration
# This configuration defines parameter combinations for random-10-10 map experiments

# Basic fixed parameters
i:
  # - assets/random-32-32-10-random-1.scen
  - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-64-64-20-random-1.scen

m:
  # - assets/random-32-32-10.map
  - assets/random-64-64-20.map

N: [200,400,600,800,1000] 
v: 3
S: 100

"&N_horizon_collab": 
  properties:
    - N
    - lacam_horizon

# LG parameters
lg: true
lifelong: true
lg_window: 10
lacam_horizon: [3, 5, 10, 15, 20]
# lifelong_seed_mode: ["plan", "local_guide"]

time_limit_sec: 50

# Plot settings
plot_settings:
  mode: violin
  line: lacam_horizon
  hide_scatter: true
  hide_data_label: true
  violin_params:
    y_axis: throughput_tasks
    x_axis: lacam_horizon
    title: title
    x_label: x_label
    x_type: int
    y_label: y_label
    orient: vertical