# LG-LACAM random-10-10 experiment configuration
# This configuration defines parameter combinations for random-10-10 map experiments

# Basic fixed parameters
i:
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-1.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-2.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-3.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-4.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-5.scen
  - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-6.scen
  - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-7.scen
  - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-8.scen
  - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-9.scen
  - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-10.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-11.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-12.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-13.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-14.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-15.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-16.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-17.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-18.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-19.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-20.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-21.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-22.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-23.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-24.scen
  # - assets/asset_for_benchmark/mapf-scen-random/scen-random/random-32-32-20-random-25.scen
m:
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  # - assets/asset_for_benchmark/mapf-map/random-32-32-20.map
  
N: 400
v: 3

baseline_without_lg:
  lg: false
  gg: false
baseline_with_gg:
  lg: false
  gg: true

# "&N_lg_collision_cost_collab": 
#   properties:
#     - N
#     - lg_collision_cost

"&lg_window_collision_cost_collab": 
  properties:
    - lg_window
    - lg_collision_cost

# LG parameters
lg: true
gg: false
# lg_window: 6
# lg_num_refine: [0, 1, 2, 3]
# lg_window: [4, 8, 12, 16, 20]
# lg_window: [6, 7, 8, 15, 20]
lg_window: [5, 10, 15, 20, 25, 30]
lg_collision_cost: [0.0, 1.0, 2.0, 3.0, 4.0]
# lg_collision_sort: true
# lns: true
# time_limit_sec: 2

# lg_pruning: true
# lg_pruning_rate: [0.8, 0.9, 1.0]
time_limit_sec: 20

# Plot settings
plot_settings:
  mode: violin
  line: lg_window
  hide_scatter: true
  hide_data_label: false
  violin_params:
    # y_axis: soc_normalized
    y_axis: benchmark_normalized
    title: title
    x_label: null
    y_label: null
    orient: vertical